### ISSUE TITLE
Missing data to place map pngs 

### ISSUE THREAD

**Issue by Conner-Schaffer** [alborrajo/DDOn-Tools#19]
You're searching StageMap.json for IDs, all the ones that don't show up just aren't in there.

for example, it's ID is 404, but its stageNo is 952, and it doesn't exist in StageMap, I added my own entry to validate and tadah!
![image](https://github.com/alborrajo/DDOn-Tools/assets/42190924/05618fd3-f238-4a98-956f-fc199ad44a94)

for this specific case its offset a bit much, and the file names should be flipped, (layer 0 is a random tiny part of the map, while layer 1 is 99% of the map), but this is most likely a case-by-case basis.
![image](https://github.com/alborrajo/DDOn-Tools/assets/42190924/ed3fe4f8-54a8-4c53-b035-134ece2f1789)

**Comment by alborrajo** [comment]
With commit 6e2b8054890fe6fe96fa8b038bc4ff593c0e726b, all rm (room) maps have been added, however, pd (parts dungeon) maps are still missing in S2 and S3 areas. This seems to be because, for S2, they migrated from having that data in a file called stage_map, which is what was extracted to obtain the pd maps up until now, to storing the pd maps somewhere else. My current guess is that they're stored in the rStageCustom and rStageCustomPartsEx files inside each stage's arc file. I've yet to check it properly

**Comment by alborrajo** [comment]
Solved with commit 2cda8b09f026ce6864ab7e3d0f18fd9c3645bef8
